---
- name: This is to install git and httpd
  hosts: Dev
  user: ansible
  become: yes
  tasks:
    - name: Install git and httpd
      yum: pkg={{item}} state=installed
      with_items:
        - httpd
        - git
